/* This file is automatically generated.  Do not edit. */
import { type t$2 as t$2, x$1 as x$3, f$3 as f$4 } from "./mod.rts.ts";
import { expect as expect$5 } from "vitest";
export const y$1: t$2 = x$3 + f$4;
console.log(expect$5);
console.log(y$1);

//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uL21haW4ucnRzIiwiLi4vbW9kLnJ0cyJdLCJuYW1lcyI6WyJ5IiwidCIsIngiLCJmIiwiY29uc29sZSIsImxvZyIsImV4cGVjdCJdLCJtYXBwaW5ncyI6Ijs7O09BRUEsTUFBTUEsR0FBQyxFQUFFQyxJQUFFLEVBQUVDLElBQUUsRUNHeUJDO0FERnhDQyxPQUFPLENBQUNDLEdBQUcsQ0FBQ0MsUUFBTTtBQUNsQkYsT0FBTyxDQUFDQyxHQUFHLENBQUNMLEdBQUMiLCJmaWxlIjoibWFpbi5ydHMudHMifQ==
